import { Inter } from "next/font/google";
import "./globals.css";
import PrelineScript from "./PrelineScript";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Resource Minifier",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        {children}
        <PrelineScript />
      </body>
    </html>
  );
}
